### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by leotran1987** [willfenton/slowed-reverb#1]
Please let me know the reason of this issue:
Many Thanks!!!!!!
-----
D:\slowed-reverb-master\slowed-reverb-master>py slowed-reverb.py -a song.mp3 -g video.gif -o slowed-reverb.mp4
Traceback (most recent call last):
  File "C:\_DEV 2021\DEEPFAKE\slowed-reverb-master\slowed-reverb-master\slowed-reverb.py", line 106, in <module>
    main()
  File "C:\_DEV 2021\DEEPFAKE\slowed-reverb-master\slowed-reverb-master\slowed-reverb.py", line 82, in main
    fx(audio_path, temp_audio_path)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pysndfx\dsp.py", line 368, in __call__
    infile = FilePathInput(src)
  File "C:\Users\Admin\AppData\Roaming\Python\Python39\site-packages\pysndfx\sndfiles.py", line 29, in __init__
    stdout, stderr = Popen(shlex.split(info_cmd, posix=False),
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by willfenton** [comment]
Hey, basically this script doesn't really work on Windows (I mean you can try to get it working but it seems tricky).
I pushed an update that added a Docker version, you can try that out. Hopefully it works out for you! Check the readme
